ENCODER_ENABLE = no
ENCODER_MAP_ENABLE = no

DYNAMIC_KEYMAP_ENABLE		= no
DYNAMIC_MACRO_ENABLE		= no
KEY_OVERRIDE_ENABLE			= no
REPEAT_KEY_ENABLE			= yes
EXTRAKEY_ENABLE				= yes
MOUSEKEY_ENABLE				= yes
CAPS_WORD_ENABLE			= yes
LAYER_LOCK_ENABLE			= yes

UNICODE_COMMON				= yes
UNICODE_ENABLE				= yes
UNICODEMAP_ENABLE			= no
UCIS_ENABLE					= no

AUTOCORRECT_ENABLE			= no
TAP_DANCE_ENABLE			= no
COMBO_ENABLE				= no
AUTO_SHIFT_ENABLE			= no
GRAVE_ESC_ENABLE			= no
SPACE_CADET_ENABLE			= no
